apiVersion: v1
kind: Pod
metadata:
    name: guestbook-pod
    labels:
        app: demo-guestbook-app
        name: guestbook-pod
spec:
    containers:
      - name: guestbook-app
        image: kubernetes/guestbook:v2
        ports:
        - containerPort: 80
