apiVersion: v1
kind: Pod
metadata:
    name: redis1-pod
    labels:
        name: redis1-pod
        app: demo-guestbook-app
spec:
  containers:
    - name: redis1
      image: redis
      ports:
        - containerPort: 6379
