apiVersion: v1
kind: Service
metadata:
    name: redis1-service
    labels:
      name: redis1-service
      app: demo-guestbook-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis1-pod
    app: demo-guestbook-app
